version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main  

jobs:
  build:
    working_directory: ~/SimpleApp
    docker:
      - image: circleci/node:18.17.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

 
